### ISSUE TITLE
Registering crashes the backend (cause yet to be known)

### ISSUE THREAD

**Issue by Lamby777** [Lamby777/SparkletX#14]
Sh33py boi did a little bit of trolling.
Logs, for reference later:

```
[nodemon] starting `node app.js`
Listening on port 3000
Failed "Register" on
Failed "Register" on Jeff was a crewmate on a spaceship traveling through the galaxy. He had always been fascinated by space and the unknown, and being a part of this mission was a dream come true for him. However, there was a darker side to Jeff that nobody knew about - he was the imposter.  Jeff had always been an excellent liar, and his ability to deceive others was second to none. He had managed to keep his true identity hidden from the rest of the crew, and they all trusted him implicitly. Jeff knew that he could use this trust to his advantage.  As the crew carried out their tasks, Jeff carefully watched them, biding his time. He knew that he had to strike when the time was right, and he was patient enough to wait. One by one, the crewmates were eliminated, and nobody suspected Jeff. They all thought that they were simply unlucky, and that the imposter was still among them.  Eventually, it was just Jeff and one other crewmate left. Jeff knew that he had to be careful - he couldn't afford to make any mistakes now. He decided to sabotage the ship's systems, and then lured his final victim into a dark corner of the ship. The crewmate had no idea what was happening until it was too late. Jeff had killed him.  With all the crewmates eliminated, Jeff emerged victorious. He had accomplished his mission as the imposter, and nobody had suspected him. However, as he looked out of the spaceship's window into the vast expanse of space, he couldn't help but feel a sense of emptiness. He had achieved his goal, but at what cost? He had betrayed the trust of his fellow crewmates, and he knew that he would have to live with that for the rest of his life.  As the spaceship continued on its journey, Jeff sat alone, wondering if it was all worth it. He knew that he would never be able to forget what he had done, and that the guilt would haunt him forever. In the end, he realized that sometimes, the price of victory can be too high.
Failed "Register" on Jeff was a crewmate on a spaceship traveling through the galaxy. He had always been fascinated by space and the unknown, and being a part of this mission was a dream come true for him. However, there was a darker side to Jeff that nobody knew about - he was the imposter.  Jeff had always been an excellent liar, and his ability to deceive others was second to none. He had managed to keep his true identity hidden from the rest of the crew, and they all trusted him implicitly. Jeff knew that he could use this trust to his advantage.  As the crew carried out their tasks, Jeff carefully watched them, biding his time. He knew that he had to strike when the time was right, and he was patient enough to wait. One by one, the crewmates were eliminated, and nobody suspected Jeff. They all thought that they were simply unlucky, and that the imposter was still among them.  Eventually, it was just Jeff and one other crewmate left. Jeff knew that he had to be careful - he couldn't afford to make any mistakes now. He decided to sabotage the ship's systems, and then lured his final victim into a dark corner of the ship. The crewmate had no idea what was happening until it was too late. Jeff had killed him.  With all the crewmates eliminated, Jeff emerged victorious. He had accomplished his mission as the imposter, and nobody had suspected him. However, as he looked out of the spaceship's window into the vast expanse of space, he couldn't help but feel a sense of emptiness. He had achieved his goal, but at what cost? He had betrayed the trust of his fellow crewmates, and he knew that he would have to live with that for the rest of his life.  As the spaceship continued on its journey, Jeff sat alone, wondering if it was all worth it. He knew that he would never be able to forget what he had done, and that the guilt would haunt him forever. In the end, he realized that sometimes, the price of victory can be too high.
/home/mira/SparkletX/node_modules/libdx/index.js:93
        return input.search(regex) !== -1;
                     ^

TypeError: Cannot read properties of undefined (reading 'search')
    at Object.containsSpecials (/home/mira/SparkletX/node_modules/libdx/index.js:93:22)
    at /home/mira/SparkletX/app.js:107:21
    at Layer.handle [as handle_request] (/home/mira/SparkletX/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/mira/SparkletX/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/mira/SparkletX/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/mira/SparkletX/node_modules/express/lib/router/layer.js:95:5)
    at /home/mira/SparkletX/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/mira/SparkletX/node_modules/express/lib/router/index.js:346:12)
    at next (/home/mira/SparkletX/node_modules/express/lib/router/index.js:280:10)
    at serveStatic (/home/mira/SparkletX/node_modules/serve-static/index.js:75:16)

Node.js v19.6.0
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Lamby777** [comment]
So it's not the super long username, but checking my old-ass code for the registration backend, I'm starting to think it's caused by using an API tester or something like that to send a register request with no username.
